server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hasanaliev?currentSchema=j922
    username: postgres
    password: culoesse123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yml
